<?php
/*
 * USER TABLE
 */
"CREATE TABLE IF NOT EXISTS users(
uId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NULL,
email VARCHAR(100) NOT NULL UNIQUE ,
gender VARCHAR(10) NOT NULL,
username VARCHAR(50) NULL,
birthdate TIMESTAMP NULL,
phone VARCHAR(20) NULL,
bio TEXT NULL,
password VARCHAR(128) NOT NULL,
address TEXT NULL,
lastLogin TIMESTAMP NULL,
acCreation TIMESTAMP NOT NULL,
status VARCHAR(20) NOT NULL,
userType VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";

/*
 * USER META/EXTRA TABLE
 */
"CREATE TABLE IF NOT EXISTS users_extra(
dataID bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
uId bigint UNSIGNED NOT NULL,
metaKey VARCHAR(50) NOT NULL,
metaValue TEXT NULL,
creation TIMESTAMP NOT NULL,
status VARCHAR(20) NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE RESTRICT 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";

/*
 * ACTIVATION KEY STORE
 */
$sql = "CREATE TABLE IF NOT EXISTS activation_key(
uId bigint UNSIGNED NOT NULL,
activationKey VARCHAR(50) NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * PROJECT CREATION INFORMATION
 */
"CREATE TABLE IF NOT EXISTS projects(
pId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
uId bigint UNSIGNED NOT NULL,
pName VARCHAR(200) NOT NULL,
projectId VARCHAR(200) NOT NULL,
description text NULL,
pCreation TIMESTAMP NOT NULL,
status VARCHAR(20) NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * Storing Uploaded Sentences
 */
"CREATE TABLE IF NOT EXISTS sentences(
sId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
uId bigint UNSIGNED NOT NULL,
projectId VARCHAR(200) NOT NULL,
sourceSentence text NOT NULL,
sCreation TIMESTAMP NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * Storing Glossary
 */

"CREATE TABLE IF NOT EXISTS glossary(
gId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
uId bigint UNSIGNED NOT NULL,
enUS VARCHAR(255) NOT NULL,
bnBD VARCHAR(300) NOT NULL,
pos VARCHAR(100) NULL,
description VARCHAR(300) NULL,
gCreation TIMESTAMP NOT NULL ,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * List of Skipping Sentences
 */
"CREATE TABLE IF NOT EXISTS list_of_skip(
skipId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
sId bigint UNSIGNED NOT NULL,
uId bigint UNSIGNED NOT NULL,
projectId VARCHAR(200) NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (sId) REFERENCES sentences(sId) 
   ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * Translated Sentences
 */
"CREATE TABLE IF NOT EXISTS translated(
tId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
sId bigint UNSIGNED NOT NULL,
uId bigint UNSIGNED NOT NULL,
projectId VARCHAR(200) NOT NULL,
targetText text NOT NULL,
tCreation TIMESTAMP NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (sId) REFERENCES sentences(sId) 
   ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * Invited User
 */

"CREATE TABLE IF NOT EXISTS inviteduser(
iuId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
pId VARCHAR(200) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
/*
 * Project Collaboration or Project Group
 */
$sql="CREATE TABLE IF NOT EXISTS projectCollaboration(
iuId bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
pId VARCHAR(200) NOT NULL,
uId bigint UNSIGNED NOT NULL,
FOREIGN KEY (uId) REFERENCES users(uId) 
   ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_general_ci";
